-- MySQL Script generated by MySQL Workbench
-- Tue Dec 22 15:32:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hrycyka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hrycyka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hrycyka` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hrycyka` ;

-- -----------------------------------------------------
-- Table `hrycyka`.`gospodarstwo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`gospodarstwo` (
  `numer_gospodarstwa` VARCHAR(14) NOT NULL,
  `wlasciciel` VARCHAR(50) NULL DEFAULT NULL,
  `REGON` VARCHAR(9) NULL DEFAULT NULL,
  `adres` VARCHAR(50) NULL DEFAULT NULL,
  `numer_telefonu` VARCHAR(9) NULL DEFAULT NULL,
  `jednostka_nadzorujaca` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`numer_gospodarstwa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`spoldzielnia_mleczarska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`spoldzielnia_mleczarska` (
  `ID_spoldzielni` VARCHAR(4) NOT NULL,
  `nazwa_spoldzielni` VARCHAR(40) NULL DEFAULT NULL,
  `adres` VARCHAR(40) NULL DEFAULT NULL,
  `oddzial` VARCHAR(10) NULL DEFAULT NULL,
  `nr_gospodarstwa_odbior_mleka` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ID_spoldzielni`),
  INDEX `nr_gospodarstwa_odbior_mleka` (`nr_gospodarstwa_odbior_mleka` ASC) VISIBLE,
  CONSTRAINT `spoldzielnia_mleczarska_ibfk_1`
    FOREIGN KEY (`nr_gospodarstwa_odbior_mleka`)
    REFERENCES `hrycyka`.`gospodarstwo` (`numer_gospodarstwa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`siedziba_stada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`siedziba_stada` (
  `numer_siedziby_stada` VARCHAR(10) NOT NULL,
  `stan_aktywnosci` ENUM('aktywna', 'spoczynek') NULL DEFAULT NULL,
  `gospodarstwo_nr` VARCHAR(14) NULL DEFAULT NULL,
  `odbior_mleka` ENUM('tak', 'nie') NULL DEFAULT NULL,
  PRIMARY KEY (`numer_siedziby_stada`),
  INDEX `gospodarstwo_nr` (`gospodarstwo_nr` ASC) VISIBLE,
  CONSTRAINT `siedziba_stada_ibfk_1`
    FOREIGN KEY (`gospodarstwo_nr`)
    REFERENCES `hrycyka`.`gospodarstwo` (`numer_gospodarstwa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`typ_bydla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`typ_bydla` (
  `id_typu` INT NOT NULL AUTO_INCREMENT,
  `nazwa_typu` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_typu`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`bydlo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`bydlo` (
  `Lp` INT NULL DEFAULT NULL,
  `nr_kolczyka` VARCHAR(9) NOT NULL,
  `typ` INT NOT NULL,
  `data_urodzenia` DATE NULL DEFAULT NULL,
  `gatunek` VARCHAR(9) NULL DEFAULT NULL,
  `kod_rasy` ENUM('HO', 'RW', 'BS', 'HH', 'BN', 'SH', 'JM', 'SE', 'MO') NULL DEFAULT NULL,
  `plec` ENUM('samica XX', 'samiec XY') NULL DEFAULT NULL,
  `typ_uzytkowy` ENUM('mleczny', 'kombinowany', 'miesny') NULL DEFAULT NULL,
  `czy_wystawa` ENUM('tak', 'nie') NULL DEFAULT NULL,
  `nr_siedziby` VARCHAR(10) NOT NULL,
  `nr_matki` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`nr_kolczyka`),
  INDEX `nr_siedziby` (`nr_siedziby` ASC) VISIBLE,
  INDEX `typ` (`typ` ASC) VISIBLE,
  CONSTRAINT `bydlo_ibfk_1`
    FOREIGN KEY (`nr_siedziby`)
    REFERENCES `hrycyka`.`siedziba_stada` (`numer_siedziby_stada`),
  CONSTRAINT `bydlo_ibfk_2`
    FOREIGN KEY (`typ`)
    REFERENCES `hrycyka`.`typ_bydla` (`id_typu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`badanie_mleka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`badanie_mleka` (
  `numer_probki` INT NOT NULL,
  `data_wykonania` DATE NULL DEFAULT NULL,
  `komorki_somatyczne` INT NULL DEFAULT NULL,
  `mocznik` INT NULL DEFAULT NULL,
  `bakterie` INT NULL DEFAULT NULL,
  `nr_krowy` VARCHAR(9) NOT NULL,
  `spoldzielnia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`numer_probki`),
  INDEX `spoldzielnia` (`spoldzielnia` ASC) VISIBLE,
  INDEX `nr_krowy` (`nr_krowy` ASC) VISIBLE,
  CONSTRAINT `badanie_mleka_ibfk_1`
    FOREIGN KEY (`spoldzielnia`)
    REFERENCES `hrycyka`.`spoldzielnia_mleczarska` (`ID_spoldzielni`),
  CONSTRAINT `badanie_mleka_ibfk_2`
    FOREIGN KEY (`nr_krowy`)
    REFERENCES `hrycyka`.`bydlo` (`nr_kolczyka`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`choroba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`choroba` (
  `id_choroby` VARCHAR(5) NOT NULL,
  `nazwa_choroby` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id_choroby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`weterynarz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`weterynarz` (
  `id_weterynarza` VARCHAR(5) NOT NULL,
  `gabinet_weterynaryjny` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`id_weterynarza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`leczenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`leczenie` (
  `nr_leczenia` VARCHAR(3) NOT NULL,
  `podane_leki` VARCHAR(50) NULL DEFAULT NULL,
  `czy_wyleczono` VARCHAR(30) NULL DEFAULT NULL,
  `nr_leczonego_zw` VARCHAR(9) NOT NULL,
  `weterynarz` VARCHAR(5) NULL DEFAULT NULL,
  `choroba` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`nr_leczenia`),
  INDEX `weterynarz` (`weterynarz` ASC) VISIBLE,
  INDEX `nr_leczonego_zw` (`nr_leczonego_zw` ASC) VISIBLE,
  INDEX `choroba` (`choroba` ASC) VISIBLE,
  CONSTRAINT `leczenie_ibfk_1`
    FOREIGN KEY (`weterynarz`)
    REFERENCES `hrycyka`.`weterynarz` (`id_weterynarza`),
  CONSTRAINT `leczenie_ibfk_2`
    FOREIGN KEY (`nr_leczonego_zw`)
    REFERENCES `hrycyka`.`bydlo` (`nr_kolczyka`),
  CONSTRAINT `leczenie_ibfk_3`
    FOREIGN KEY (`choroba`)
    REFERENCES `hrycyka`.`choroba` (`id_choroby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`typ_zdarzenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`typ_zdarzenia` (
  `id_typu_zdarzenia` INT NOT NULL AUTO_INCREMENT,
  `nazwa_typu_zdarzenia` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_typu_zdarzenia`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hrycyka`.`zdarzenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrycyka`.`zdarzenie` (
  `id_zdarzenia` INT NOT NULL AUTO_INCREMENT,
  `typ_zdarzenia` INT NULL DEFAULT NULL,
  `data_zdarzenia` DATE NULL DEFAULT NULL,
  `wpis_do_ksiegi` VARCHAR(30) NULL DEFAULT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `nr_kolczyka` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_zdarzenia`),
  INDEX `nr_kolczyka` (`nr_kolczyka` ASC) VISIBLE,
  INDEX `typ_zdarzenia` (`typ_zdarzenia` ASC) VISIBLE,
  CONSTRAINT `zdarzenie_ibfk_1`
    FOREIGN KEY (`nr_kolczyka`)
    REFERENCES `hrycyka`.`bydlo` (`nr_kolczyka`),
  CONSTRAINT `zdarzenie_ibfk_2`
    FOREIGN KEY (`typ_zdarzenia`)
    REFERENCES `hrycyka`.`typ_zdarzenia` (`id_typu_zdarzenia`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `hrycyka` ;

-- -----------------------------------------------------
-- function liczba_stada
-- -----------------------------------------------------

DELIMITER $$
USE `hrycyka`$$
CREATE DEFINER=`hrycyka`@`localhost` FUNCTION `liczba_stada`() RETURNS int
BEGIN
    DECLARE ilosc_stada INT;
    SELECT COUNT(*) INTO @ilosc_stada FROM bydlo;
    RETURN @ilosc_stada;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usun_martwe_zwierze
-- -----------------------------------------------------

DELIMITER $$
USE `hrycyka`$$
CREATE DEFINER=`hrycyka`@`localhost` PROCEDURE `usun_martwe_zwierze`()
BEGIN
DELETE FROM bydlo WHERE (SELECT b.nr_kolczyka FROM bydlo AS b INNER JOIN zdarzenie AS z ON b.nr_kolczyka=z.nr_kolczyka WHERE z.id_zdarzenia=4);
END$$

DELIMITER ;
USE `hrycyka`;

DELIMITER $$
USE `hrycyka`$$
CREATE
DEFINER=`hrycyka`@`localhost`
TRIGGER `hrycyka`.`czy_wyleczono`
BEFORE INSERT ON `hrycyka`.`leczenie`
FOR EACH ROW
BEGIN
IF NEW.czy_wyleczono ='tak' 
THEN
SET NEW.czy_wyleczono ='tak, podano leki';
END IF;
END$$

USE `hrycyka`$$
CREATE
DEFINER=`hrycyka`@`localhost`
TRIGGER `hrycyka`.`czy_wpis`
BEFORE INSERT ON `hrycyka`.`zdarzenie`
FOR EACH ROW
IF NEW.wpis_do_ksiegi = NULL
THEN
SET NEW.wpis_do_ksiegi = 'tak';
END IF$$

USE `hrycyka`$$
CREATE
DEFINER=`hrycyka`@`localhost`
TRIGGER `hrycyka`.`wpisanie_do_ksiegi`
BEFORE INSERT ON `hrycyka`.`zdarzenie`
FOR EACH ROW
IF NEW.wpis_do_ksiegi = NULL
THEN
SET NEW.wpis_do_ksiegi = 'tak';
END IF$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
